### ISSUE TITLE
Adding of oauth request module in nginx config in devlake-ui-config

### ISSUE THREAD

**Issue by rs287** [apache/devlake#5353]
## Question
Would it be possible to tweak nginx conf file in devlake ui config and add "oauth request module" (for adding OAUTH authorization server), packaged this in helm chart (common step)?
**nginx.conf** 
```

server {
  listen 4000;
  server_name localhost;
  absolute_redirect off;
  ${SERVER_CONF}

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri /index.html;
  }

  location /api/ {
    # OAuth2 authentication
    auth_request /oauth2/auth;
    error_page 401 = /oauth2/error;


    # Proxy settings
    resolver ${DNS} valid=${DNS_VALID};
    resolver_timeout 3s;
    set $target "${DEVLAKE_ENDPOINT}";
    rewrite /api/(.*) /$1 break;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
    proxy_pass ${DEVLAKE_ENDPOINT_PROTO}://$target;
  }

  location = /oauth2/auth {
    internal;
    proxy_pass ${AUTH_SERVER_ENDPOINT};
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header X-Original-URI $request_uri;
  }
```
Any help is highly appreciated in checking this?

**Comment by klesh** [comment]
@rs287 we recently had some discussions regarding this matter, and we came to believe the [oauth2_proxy](https://github.com/apache/incubator-devlake/issues/5140#issuecomment-1550492466) is a better approach, that is: to set up oauth2_proxy as reverse-proxy before `config-ui`. Because:

1. Not all users need it and the actual settings would be quite different from user to user.
2. We don't recommend to mount the nginx.conf as well because it will be updated from time to time to support some new features.
