### ISSUE TITLE
[Bug] Boards from certain plugins don't have `_raw_data_table` and can't be deleted

### ISSUE THREAD

**Issue by Startrekzky** [apache/devlake#5587]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

![image](https://github.com/apache/incubator-devlake/assets/14050754/92ce78b5-5f6c-4b7c-a713-61ee9da74369)

### What do you expect to happen

The boards from GitHub, BitBucket, Azure, Zentao, etc. should have values in `_raw_data_table`

### How to reproduce

N/A

### Version

v0.18.0-alpha11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by keon94** [comment]
This is going to be the case with boards collected prior to the Delete feature

**Comment by hezyin** [comment]
Some questions to think about:

1. Does this only affect the issue tracking domain or all domains? I assume the answer is all domains even though this issue only reports boards missing `_raw_data_table` values.
2. @Startrekzky Can you confirm that those rows without `_raw_data_table` values were collected prior to the Delete feature? Just want to make sure we're correctly diagnosing the root cause.
3. Does that mean for users upgrading from v0.17, would have to re-save all data scopes and re-run all projects in order to have data correctly migrated to v0.18 format?
4. How much manual work is involved in this process and do we think users can follow the upgrade instructions easily?
5. What would be the consequences if users weren't able to follow the instructions correctly?

**Comment by klesh** [comment]
@keon94 @hezyin @Startrekzky No, we don't ask users to manually modify each of every scope they have in the database, it would not be practical or acceptable.

We should add migration scripts to do it automatically

**Comment by keon94** [comment]
@klesh I was going ask how we'd know the plugin of origin in the domain-scope tables, but just realized that the IDs contain the plugin-name in them, so it should be possible to write a migration-script that infers the plugin from each PK, and writes it to the raw_params_table column.

**Comment by Startrekzky** [comment]
This issue has been done.
