### ISSUE TITLE
[Feature][Gitlab] Support Issue-type transformations in Gitlab Blueprint

### ISSUE THREAD

**Issue by batjko** [apache/devlake#5760]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

When going through my data scope for the Giltab connection, and trying to add a transformation to any of the Gitlab repositories, I only ever get the CI/CD Transformation option.
I can only assume that's a limitation of the connector at the moment, because I do also have issue tracking among my selected scopes, so I would expect this to show up.

So I would like to also add transformations for Giltab _issues_ on those projects.

### Description

E.g. currently, when I select transformation for any Gitlab repositories, I see only this:

![image](https://github.com/apache/incubator-devlake/assets/7287076/61cee941-09a6-4c19-9da9-066815666679)

However, as per documentation, I would like to also apply issue transformations, so I would assume this:

![image](https://github.com/apache/incubator-devlake/assets/7287076/4091f905-d55a-4d37-885d-8b74d2acba6e)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by batjko** [comment]
In fact, I have all entities selected, but I don't get _any_ of the other transformation types, except for CI/CD.

![image](https://github.com/apache/incubator-devlake/assets/7287076/d7e2eba4-a4f1-4db2-860f-6914a1f9553d)

**Comment by abeizn** [comment]
@Startrekzky @yumengwang03 Can you take a look?

**Comment by Startrekzky** [comment]
Hi @batjko , sorry for the late reply. May I ask:
1. what specific types of GitLab issues do you use?
2. what's your goal of transforming them to standard types? 

I asked because there's a default `Incident` type in GitLab issues, so the DORA metrics should not have been affected without any issue transformations.

**Comment by Startrekzky** [comment]
@batjko DevLake is not hiding anything in the UI. DevLake doesn't support issue-transformation configuration simply because not many users use GitLab issues to manage requirements/feature requests, so we don't find the necessity of doing it. 

On the contrary, DevLake's GitHub plugin provides the issue-transformation configuration based on GitHub's issue labels, as many users use GitHub issues to manage requirements or bugs.

Does it make sense?

**Comment by clement-igonet** [comment]
> Incident that is used to measure DORA metrics is a system issue type in GitLab, unlike Jira issue types or GitHub's issue labels, so it doesn't need to be transformed.
What are the rule to import gitlab `incident` as devlake `issue` with `type`=`INCIDENT` ?

**Comment by Startrekzky** [comment]
> So, what are the rules to import gitlab `incident` as devlake `issue` with `type`=`INCIDENT` ?

Hi @clement-igonet . DevLake should collect GitLab incidents and covert them to `type = INCIDENT`by default. If the actuall behavior doesn't meet this logic, then there's a bug.

**Comment by xiaomingzhang12** [comment]
I tried it out, and in GitLab, data of the 'incident' type can be successfully collected, but the 'type' field in the 'issues' table remains empty. @Startrekzky 
![image](https://github.com/apache/incubator-devlake/assets/142298906/306eb763-ba99-4368-88f6-1892fb2f16f4)

**Comment by clement-igonet** [comment]
So, could we re-open the current topic ?
