### ISSUE TITLE
[Feature] Add Developer Certificate of Origin check in the CI 

### ISSUE THREAD

**Issue by shubham-cmyk** [apache/devlake#5862]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

It would help use the user that is responsible for the particular commit. Also is a standard practice 

### Description

Learn more about the signing the commit : https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

Look here about the DCO : https://probot.github.io/apps/dco/

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shubham-cmyk** [comment]
@klesh Would you consider this adding

**Comment by klesh** [comment]
It is good practice and I'm fine with it myself.
However, from what I can tell, most developers do not familiar with GPG and signing commits, it would be quite a learning curve, especially when most of our contributors are using macOS or Windows...🥲
I think it is fine not to sign the commits since we are reviewing every PRs and honestly, author forgery is not a problem so far.

**Comment by shubham-cmyk** [comment]
Okay fine but this should be considered to be added in the future.
