### ISSUE TITLE
[Bug][Bamboo] In the cicd_pipeline_commits table, the value of the repo_url field is incorrect

### ISSUE THREAD

**Issue by xiaomingzhang12** [apache/devlake#6083]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

In the testing environment, collect the plan p1 under project xm-1. After the collection is completed, check the data in the cicd_pipeline_commits table
![image](https://github.com/apache/incubator-devlake/assets/142298906/ac23707a-c38b-497a-9d43-8f9bfa971266)

### What do you expect to happen

The expectation is the url of the repo where the commit associated with the pipeline is located.

### How to reproduce

See above

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by d4x1** [comment]
I can not fetch a repo's orginal url so far. Do you have any advice? @Startrekzky

**Comment by Startrekzky** [comment]
> I can not fetch a repo's orginal url so far. Do you have any advice? @Startrekzky

I asked ChatGPT, can you try it out?
![image](https://github.com/apache/incubator-devlake/assets/14050754/f7779485-95a5-42e7-a2e9-a4c9efe3f1d3)

**Comment by d4x1** [comment]
@Startrekzky  I have tried ChatGPT's advice, and the api is work, but its returns are like this:
![image](https://github.com/apache/incubator-devlake/assets/5844806/0c7ecec2-4a71-4f9b-8381-13a3feaa6fc0)

It has some information about vcs info, but no field named repoXxx. So ChatGPT's answer is suitable for this issue.

BTW, I have tried with @klesh  and find we can get project's repos(only repositories are configurated in project' settings), it's an API like this:
[`HTTP GET /rest/api/latest/project/{project_key}/repository`](https://developer.atlassian.com/server/bamboo/rest/api-group-api/#api-api-latest-project-projectkey-repositories-get), its return is:
```json
[
	{
		"id": 123,
		"name": "apache/incubator-devlake",
		"url": "http://ip:port/admin/configureLinkedRepositories.action?repositoryId=123",
		"rssEnabled": false
	}
]
```
the URL field is an link to repo's homepage in bamboo, not third party's link. 
So we infer that  there is no field named `repo_url` needed by devlake, we have to concat repo's url case by case.

More additional detail will be fetched when we spent some time diving into bamboo's database. I think is workable cause of this [QA](https://community.atlassian.com/t5/Bamboo-questions/Bamboo-REST-API-to-retrieve-repositories-of-the-plan/qaq-p/795842).

**Comment by d4x1** [comment]
After discussing with @klesh and @xiaomingzhang12, we find even if `repo_url` field is empty,  the DORA metrics can be caculated correctly as long as it stands for a repo uniquely. So the concusion is we will update `repo_url` field like `fake://ip:port/repos/{repo_id_in_bamboo}`.

More details about fetching repo's original url from Bamboo's database(table: VCS_LOCATION, column: XML_DEFINITION_DATA), it is feasible. But there are many situations we need to handle because Bamboo can be deployed with different databases, and `XML_DEFINITION_DATA`'s content is different according to the repo's type(github/bitbucket and so on). It is a huge work to make repo url correctly and abviously it is not devlake's focus at now. So we will handle it as simpliy as posiible. 

Hope this comment is helpful.
