### ISSUE TITLE
[Bug][Advanced Mode] Unable to trigger blueprint with Refdiff plugin

### ISSUE THREAD

**Issue by ghost** [apache/devlake#6766]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Getting error 
error triggering blueprint Wraps: (2) empty plan Error types: (1) *hintdetail.withDetail (2) *errors.errorString

### What do you expect to happen

Data enrichment on the data collected from bitbucket

### How to reproduce

Use the gitextractor to collect details from bitbucket server and run refdiff

### Anything else

None

### Version

v0.19.0-beta3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
Advanced Mode?
Check `plan` make sure it is not empty

**Comment by FTNJAYABA** [comment]
Thank you @klesh ! I was able to make it work by combining gitextractor and refdiff into subtasks in a single pipeline. However, I'm unbale to see data in the pr_requests table. 
My intent was to use the refdiff in place of bitbucket connector. Since we have a bitbucket server, I'm unable to use the delivered connector.

Is there a workaround, so that I'm able to generate the PR metrics?

**Comment by klesh** [comment]
@FTNJAYABA `gitextractor` is for collecting git meta data, like commits, branches, tags, etc, and `refdiff` calculates commits that a commit ahead of another one. Both of them do not collect or produce `Pull Request` data.

The `Pull Request` belongs to and are stored  on the Platform (github/gitlab/bitbucket, etc.) instead of the `git repository` itself which mean you gonna need a Dedicated Data Source Plugin to collect PRs.

Good new is that a good fellow had contributed such a pluign via

**Comment by FTNJAYABA** [comment]
That sounds promising. Shall await the release. Thanks for helping @klesh in such a quick turnaround!
