### ISSUE TITLE
Devlake Stable version

### ISSUE THREAD

**Issue by sabari-shankar22** [apache/devlake#6805]
In devlake portal, it is mentioned as v19.0 as stable release, but under release in github there is no stable release.

Do we have any stable release for devlake?

**Comment by d4x1** [comment]
We are working on a v1.0, and it will be a very stable version. So far, in every version, we fix lots of bugs, and if bugs are critical, we will cheryy pick fixes to old version. So I think you can just use the latest version, if you don't need new features, staying on old version is acceptable.
And we have no stable release in GitHub release page, because we have some processes to follow.
