### ISSUE TITLE
[Bug][Deployment Frequency] Consider as a success production pipeline when the deploy stage has never been executed successfully

### ISSUE THREAD

**Issue by estefaniasuasti** [apache/devlake#7005]
## Question
As you can see here, we had 4 deployments during April. However, when I checked the pipelines I discovered that "4244451" never passed the deploy stage, it only passed the "dry-run" stage.  What would be the reason?
 
## Screenshots
![Screenshot 2024-02-22 at 2 31 03 PM (1)](https://github.com/apache/incubator-devlake/assets/39221859/05e7cf26-f51a-4ef1-8bfb-a2d8b0611622)
![image (54)](https://github.com/apache/incubator-devlake/assets/39221859/9e268903-43a3-4ac8-bf7a-55fecb1c0bfa)
![image](https://github.com/apache/incubator-devlake/assets/39221859/317336fb-188a-4724-8c3c-b29b4afbaffd)
![image](https://github.com/apache/incubator-devlake/assets/14050754/d11c1734-1cad-4b06-918d-12fc0a60b8e6)

## Additional context
Add any other context here.

**Comment by Startrekzky** [comment]
Hi @estefaniasuasti , may I have your version number?

**Comment by estefaniasuasti** [comment]
Good morning @Startrekzky,

**Comment by d4x1** [comment]
Sorry for my late reply. 

@estefaniasuasti 

After debugging and testing, I think the root cause is:
<img width="468" alt="image" src="https://github.com/apache/incubator-devlake/assets/5844806/7ba9b29d-4b82-4a75-944e-7b864fc160c5">

Target branch `nso/frankfurt` can be regexped in your scope config `(?i)(^(nso/frankfurt)$)`, and this will make current pipeline as `DevLake Deployment`, althrough it's jobs failed.

You can verify it by checking your database:
1. `environment` field in `cicd_deployments` should be empty(not `PRODUCTION`).
2. `type` field in `cicd_pipelines` should be `DEPLOYMENT`, `environment` field in `cicd_deployments` should be empty(not `PRODUCTION`).


FYI, I have checked code, there are some facts:

1. Table `cicd_deployments`'s data is from `cicd_pipelines` and `cicd_tasks` in most case.
3. Status `passed` in GitLab pipeline's webpage is `success` in its API response.

**Comment by estefaniasuasti** [comment]
1. Is DevLake correctly capturing the status of the pipeline? In our case "Warning" 

2. Should we consider Pipeline status or job status to determine a "Success" deployment?

**Comment by d4x1** [comment]
1.  >Is DevLake correctly capturing the status of the pipeline? In our case "Warning"

Pipeline's status is from `_raw_gitlab_api_pipeline_details.data`, there is a `status` field in it, you can check it. 
In [GitLab API](https://docs.gitlab.com/ee/api/pipelines.html#list-project-pipelines), there is no`warning` status.
![image](https://github.com/apache/incubator-devlake/assets/5844806/d0ad0040-4ffc-4b7b-88d0-8848e555ecfd)
I want to know it's value in API response too.

2.  > Should we consider Pipeline status or job status to determine a "Success" deployment?

 Of course, only success or failed pipelines or jobs can be regarded as deployments. The key field is `result` in `cicd_pipelines` and `cicd_tasks`.

I also want to know the value of `cicd_pipelines. environment` and `cicd_tasks.environment` (with `pipeline_id` = {your pipeline id}). Thank you.

**Comment by estefaniasuasti** [comment]
1.- The value is success.
<img width="1123" alt="image" src="https://github.com/apache/incubator-devlake/assets/39221859/f7c41a5e-9369-498e-9c2a-f40a50cc4900">
2.- cicd_pipelines.result = SUCCESS  and cicd_pipelines. environment = ""(empty)

**Comment by d4x1** [comment]
1.  It seems GitLab regard it as `success`,  we cannot fetch the `warning` status and can do nothing with it.
2. fields' values in cicd_tasks are within my expectation.

In cicd_pipelines, it's marked "success"(although it' warning in GitLab web page. I think it's the root cause beacuse it's not a successful pipeline in face), and in this pipeline, there is a "PRODUCTION "task. So this pipeline becomes a PRODUCTION DEPLOYMENT.

Do you have any advice about how to fix it?

**Comment by estefaniasuasti** [comment]
Hi @d4x1 ,

I think the missing part is to validate when the Environment is "Production" the Result should be "Success" in the cicd_tasks table for that specific job. In our case, the job that deploys to production is "fra-prod-deploy," and even if the other jobs fail, this is the indicator to say if it reached production or not. I think this is the only way to be 100% sure if the deployment happened in production despite the pipeline status.
