### ISSUE TITLE
[Feature][Azure DevOps] Support self-hosted Azure DevOps instance

### ISSUE THREAD

**Issue by simonrrr** [apache/devlake#7260]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a tech lead I’d like to be able to use Apache DevLake with our enterprise self-hosted instance of Azure DevOps

### Description

Please allow configuration of the Azure DevOps base API URL - in the Python code you’re using dev.azure.com, and in the go code an old VSTS one, but if you allow that to be replaced with a different base URL for self hosted (e.g. https://my.intranet.instance/tfs) the APIs are (mostly!) compatible.

Happy to take a small look at what it might take - though if you’re quickly moving over to the go library from the Python one that might take a bit longer.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by klesh** [comment]
@simonrrr Thanks for volunteering for the task. You are free to choose which language you prefer, we are open to multiple plugins for the same data source. No plan for moving of any sort.

**Comment by wouldd** [comment]
@simonrrr fwiw I'd be iterested in this. at the moment I just run a customised version in which I hardcode our internal urls. FWIW fixing this will also require tweaking the API verison on the requests since hte current implementation uses a version I think is not available on prem.
There is a small complication in the use of the graph api for some user data which is not an onprem api. I have no really noticed any isseus with just skipping htat stuff entirely for my setup.
