### ISSUE TITLE
[Feature][AzureDevOps GO/GitHub] Support extracting Azure Pipelines metrics from GitHub Repositories [Feature][Module Name] Feature title

### ISSUE THREAD

**Issue by xiaomingzhang12** [apache/devlake#7307]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

I have GitHub Repositories (Data Scopes of GitHub Plugin) and I use Azure Pipelines as a CI/CD tool. Azure Pipelines is part of AzureDevOps.

I want to be able to select GitHub Repositories and configure DevLake to extract DORA metrics from Azure Pipelines + GitHub Repo. But, today, I can only use GitHub Actions with GitHub Repositories.

### Description

In the Python implementation of the Azure DevOps plugin, this feature has already been implemented, as detailed in PR: https://github.com/apache/incubator-devlake/pull/5950

With further details described in the issue: https://github.com/apache/incubator-devlake/issues/5692. 
We are now looking to have this functionality supported in the Go implementation of the Azure DevOps plugin as well. 
Thank you.

### Related issues

https://github.com/apache/incubator-devlake/issues/5692.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mr-ks** [comment]
I initially dropped the feature as it requires the PAT to have access to the [Service Endpoint API](https://learn.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints?view=azure-devops-rest-7.1) which is the place where people usually store connections to 3rd party products such as github, azure, aws, etc. 
The scope required to read the data is `vso.serviceendpoint` which only grants read access (secrets excluded).
If everybody is fine with that, I'd also try to make it optional to not force people to grant scopes for features they don’t need or use (i.e. read the service endpoint data if the scope is available, otherwise skip it)

**Comment by klesh** [comment]
Optional looks reasonable to me.
