### ISSUE TITLE
[Bug][gitlab] The data in the commits table is different from the data in GitLab

### ISSUE THREAD

**Issue by Shikanor** [apache/devlake#7480]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

While attempting to use the commits table for a code volume analysis, I encountered an unexpected scenario: a portion of the additions in the commits table did not match the additions displayed on the GitLab page, especially following merge operations. To confirm whether this was an issue with the token, I used the same token to write a Python script for verification. The results showed that indeed, there are occasional discrepancies between the data in the commits table and the data on GitLab.

![image](https://github.com/apache/incubator-devlake/assets/115983836/f83a6674-75f2-47cc-8991-50e2d24fccf6)
![image](https://github.com/apache/incubator-devlake/assets/115983836/af6aad6d-78b0-435c-8634-906a58459a2d)
![image](https://github.com/apache/incubator-devlake/assets/115983836/d68377d6-5175-4ce8-8b67-17b3c4b63f5d)

### What do you expect to happen

I hope to minimize these discrepancies as much as possible, as I'm not sure if one day they might affect the code volume statistics for an entire individual.

### How to reproduce

First, create a feature branch from the main branch, then commit some code on the feature branch. After that, switch back to the main branch and commit changes to a different file (ensuring there are no merge conflicts). Finally, merge the feature branch back into the main branch. After the merge, click the "Collect Data" button to retrieve the commits data from the commits table and compare it with the data on GitLab.

### Version

v1.0.0-beta7@2cc08c7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Thanks for reporting.

**Comment by klesh** [comment]
It appears the `libgit2` library we're using has a different diff algorithm compared to GitLab. Unfortunately, this is likely an expected behavior rather than a bug and wouldn't be easily configurable.

**Comment by Startrekzky** [comment]
Hi, we checked the logic. The difference between additions from GitLab APIs and DevLake is because:

- DevLake doesn't use GitLab APIs, but the `gitextractor` plugin to collect `commits`
- The `gitextractor` plugin uses the `Gogit` library to calculate the commits additions and deletions.
- The logic of calculating the additions in `Gogit` and `GitLab APIs` are slightly different.

Thus, it's a problem that can not be addressed in DevLake for now. We can't switch `gitextractor` to `GitLab APIs` or `GitHub APIs` or `Bitbucket APIs` or `Bitbucket APIs` to collect commits (Git) data, as it will increase the collection time by 10x time.
