### ISSUE TITLE
[Bug][gitextractor] Error running pipeline beta5

### ISSUE THREAD

**Issue by Capone1983** [apache/devlake#7842]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Moved from beta4 to beta5. All bitbucket and github repos when step gitextractor starts - fails now. 

`attached stack trace -- stack trace: | github.com/apache/incubator-devlake/server/services.runPipeline | /app/server/services/pipeline_runner.go:79 | [...repeated from below...] Wraps: (2) Error running pipeline 261. Wraps: (3) attached stack trace -- stack trace: | github.com/apache/incubator-devlake/server/services.RunTasksStandalone | /app/server/services/task.go:217 | github.com/apache/incubator-devlake/server/services.(*pipelineRunner).runPipelineStandalone.func1 | /app/server/services/pipeline_runner.go:42 | github.com/apache/incubator-devlake/core/runner.runPipelineTasks | /app/core/runner/run_pipeline.go:90 | github.com/apache/incubator-devlake/core/runner.RunPipeline | /app/core/runner/run_pipeline.go:54 | github.com/apache/incubator-devlake/server/services.(*pipelineRunner).runPipelineStandalone | /app/server/services/pipeline_runner.go:38 | github.com/apache/incubator-devlake/server/services.runPipeline | /app/server/services/pipeline_runner.go:76 | github.com/apache/incubator-devlake/server/services.RunPipelineInQueue.func1 | /app/server/services/pipeline.go:347 | runtime.goexit | /usr/local/go/src/runtime/asm_amd64.s:1598 Wraps: (4) attached stack trace | -- stack trace: | | github.com/apache/incubator-devlake/server/services.RunTasksStandalone.func1 | | /app/server/services/task.go:189 | Wraps: (2) Error running task 26893. | Wraps: (3) attached stack trace | -- stack trace: | | github.com/apache/incubator-devlake/core/runner.RunPluginSubTasks | | /app/core/runner/run_task.go:329 | | github.com/apache/incubator-devlake/core/runner.RunPluginTask | | /app/core/runner/run_task.go:163 | | github.com/apache/incubator-devlake/core/runner.RunTask | | /app/core/runner/run_task.go:137 | | github.com/apache/incubator-devlake/server/services.runTaskStandalone | | /app/server/services/task_runner.go:113 | | github.com/apache/incubator-devlake/server/services.RunTasksStandalone.func1 | | /app/server/services/task.go:187 | Wraps: (4) subtask Clone Git Repo ended unexpectedly | Wraps: (5) attached stack trace | -- stack trace: | | github.com/apache/incubator-devlake/plugins/gitextractor/parser.(*GitcliCloner).execGitCloneCommand | | /app/plugins/gitextractor/parser/clone_gitcli.go:144 | | [...repeated from below...] | Wraps: (6) failed to fetch all branches from the remote server | Wraps: (7) attached stack trace | -- stack trace: | | github.com/apache/incubator-devlake/plugins/gitextractor/parser.(*GitcliCloner).execCommand | | /app/plugins/gitextractor/parser/clone_gitcli.go:238 | | github.com/apache/incubator-devlake/plugins/gitextractor/parser.(*GitcliCloner).execGitCommandIn | | /app/plugins/gitextractor/parser/clone_gitcli.go:227 | | github.com/apache/incubator-devlake/plugins/gitextractor/parser.(*GitcliCloner).execGitCloneCommand | | /app/plugins/gitextractor/parser/clone_gitcli.go:143 | | github.com/apache/incubator-devlake/plugins/gitextractor/parser.(*GitcliCloner).CloneRepo | | /app/plugins/gitextractor/parser/clone_gitcli.go:92 | | github.com/apache/incubator-devlake/plugins/gitextractor/tasks.CloneGitRepo | | /app/plugins/gitextractor/tasks/repo_cloner.go:57 | | github.com/apache/incubator-devlake/core/runner.runSubtask | | /app/core/runner/run_task.go:405 | | github.com/apache/incubator-devlake/core/runner.RunPluginSubTasks | | /app/core/runner/run_task.go:327 | | github.com/apache/incubator-devlake/core/runner.RunPluginTask | | /app/core/runner/run_task.go:163 | | github.com/apache/incubator-devlake/core/runner.RunTask | | /app/core/runner/run_task.go:137 | | github.com/apache/incubator-devlake/server/services.runTaskStandalone | | /app/server/services/task_runner.go:113 | | github.com/apache/incubator-devlake/server/services.RunTasksStandalone.func1 | | /app/server/services/task.go:187 | | runtime.goexit | | /usr/local/go/src/runtime/asm_amd64.s:1598 | Wraps: (8) git cmd [git fetch --depth=1 origin -c http.sslVerify=false] in /tmp/gitextractor2334407235 failed: error: unknown switch `c' | | usage: git fetch [<options>] [<repository> [<refspec>...]] | | or: git fetch [<options>] <group> | | or: git fetch --multiple [<options>] [(<repository> | <group>)...] | | or: git fetch --all [<options>] | | | | -v, --verbose be more verbose | | -q, --quiet be more quiet | | --all fetch from all remotes | | --set-upstream set upstream for git pull/fetch | | -a, --append append to .git/FETCH_HEAD instead of overwriting | | --upload-pack <path> path to upload pack on remote end | | -f, --force force overwrite of local reference | | -m, --multiple fetch from multiple remotes | | -t, --tags fetch all tags and associated objects | | -n do not fetch all tags (--no-tags) | | -j, --jobs <n> number of submodules fetched in parallel | | -p, --prune prune remote-tracking branches no longer on remote | | -P, --prune-tags prune local tags no longer on remote and clobber changed tags | | --recurse-submodules[=<on-demand>] | | control recursive fetching of submodules | | --dry-run dry run | | --write-fetch-head write fetched references to the FETCH_HEAD file | | -k, --keep keep downloaded pack | | -u, --update-head-ok allow updating of HEAD ref | | --progress force progress reporting | | --depth <depth> deepen history of shallow clone | | --shallow-since <time> | | deepen history of shallow repository based on time | | --shallow-exclude <revision> | | deepen history of shallow clone, excluding rev | | --deepen <n> deepen history of shallow clone | | --unshallow convert to a complete repository | | --update-shallow accept refs that update .git/shallow | | --refmap <refmap> specify fetch refmap | | -o, --server-option <server-specific> | | option to transmit | | -4, --ipv4 use IPv4 addresses only | | -6, --ipv6 use IPv6 addresses only | | --negotiation-tip <revision> | | report that we have only objects reachable from this object | | --filter <args> object filtering | | --auto-maintenance run 'maintenance --auto' after fetching | | --auto-gc run 'maintenance --auto' after fetching | | --show-forced-updates | | check for forced-updates on all updated branches | | --write-commit-graph write the commit-graph after fetching | | --stdin accept refspecs from stdin | Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.withPrefix (7) *withstack.withStack (8) *errutil.leafError Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError`

### What do you expect to happen

Extract of git info should be successful.  

### How to reproduce

Move from beta4 to beta5

### Version

v1.0.1-beta5@ebddfe3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Capone1983** [comment]
We should not have to change anything when moving to different versions. 
Reverted back to beta4 and its working fine again.

**Comment by Startrekzky** [comment]
@Capone1983 Got it. We'll look at it asap.

**Comment by denodaeus** [comment]
Also encountering this issue on beta5:

`Mtime="2024-08-05 14:10:04" level=error msg=" [pipeline service] [pipeline #12] run tasks failed\n\tcaused by: Error running task 81.\n\tWraps: (2) subtask Clone Git Repo ended unexpectedly\n\tWraps: (3) failed to fetch all branches from the remote server\n\tWraps: (4) git cmd [git fetch --depth=1 origin -c http.sslVerify=false] in /tmp/gitextractor3731976518 failed: error: unknown switch `c'\n\t  | usage: git fetch [<options>] [<repository> [<refspec>...]]\n\t  |    or: git fetch [<options>] <group>\n\t  |    or: git fetch --multiple [<options>] [(<repository> | <group>)...]\n\t  |    or: git fetch --all [<options>]\n\t  |\n\t  |     -v, --verbose         be more verbose\n\t  |     -q, --quiet           be more quiet\n\t  |     --all                 fetch from all remotes\n\t  |     --set-upstream        set upstream for git pull/fetch\n\t  |     -a, --append          append to .git/FETCH_HEAD instead of overwriting\n\t  |     --upload-pack <path>  path to upload pack on remote end\n\t  |     -f, --force           force overwrite of local reference\n\t  |     -m, --multiple        fetch from multiple remotes\n\t  |     -t, --tags            fetch all tags and associated objects\n\t  |     -n                    do not fetch all tags (--no-tags)\n\t  |     -j, --jobs <n>        number of submodules fetched in parallel\n\t  |     -p, --prune           prune remote-tracking branches no longer on remote\n\t  |     -P, --prune-tags      prune local tags no longer on remote and clobber changed tags\n\t  |     --recurse-submodules[=<on-demand>]\n\t  |                           control recursive fetching of submodules\n\t  |     --dry-run             dry run\n\t  |     --write-fetch-head    write fetched references to the FETCH_HEAD file\n\t  |     -k, --keep            keep downloaded pack\n\t  |     -u, --update-head-ok  allow updating of HEAD ref\n\t  |     --progress            force progress reporting\n\t  |     --depth <depth>       dee                       deepen history of shallow repository based on time\n\t  |     --shallow-exclude <revision>\n\t  |                           deepen history of shallow clone, excluding rev\n\t  |     --deepen <n>          deepen history of shallow clone\n\t  |     --unshallow           convert to a complete repository\n\t  |     --update-shallow      accept refs that update .git/shallow\n\t  |     --refmap <refmap>     specify fetch refmap\n\t  |     -o, --server-option <server-specific>\n\t  |                           option to transmit\n\t  |     -4, --ipv4            use IPv4 addresses only\n\t  |     -6, --ipv6            use IPv6 addresses only\n\t  |     --negotiation-tip <revision>\n\t  |                           report that we have only objects reachable from this object\n\t  |     --filter <args>       object filtering\n\t  |     --auto-maintenance    run 'maintenance --auto' after fetching\n\t  |     --auto-gc             run 'maintenance --auto' after fetching\n\t  |     --show-forced-updates\n\t  |                           check for forced-updates on all updated branches\n\t  |     --write-commit-graph  write the commit-graph after fetching\n\t  |     --stdin               accept refspecs from stdin\n\tError types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *hintdetail.withDetail (4) *errors.errorString\n\t"
time="2024-08-05 14:10:04" level=info msg=" [pipeline service] [pipeline #12] return error"`

**Comment by d4x1** [comment]
@denodaeus   Can you run `git fetch --depth=1 origin -c http.sslVerify=false` sucessfully in your local repo?
I think this cli should be `git -c http.sslVerify=false clone_or_fetch`.

**Comment by Startrekzky** [comment]
@dosu Could you stop labeling GitHub issues with tags starting with `pr-type/`?

**Comment by devstein** [comment]
Hey @Startrekzky apologies for the confusion here. It looks like Dosu's issue and PR label settings weren't set up correctly. I just fixed it and invited you to the web app.

If you have any other issues or question, feel free to ping me in our [community slack](https://join.slack.com/t/dosucommunity/shared_invite/zt-2l2r2csg5-9Wtkchf~WZbDdFZBDC7O0A)

**Comment by denodaeus** [comment]
Any idea when you'll have a beta6 with this change?  beta4 has a bunch of broken dashboards with bitbucket server, and beta5 won't run for me because of the above

**Comment by klesh** [comment]
Hi, All. PR #7941 should fix the ssl verify problem.
