### ISSUE TITLE
[Feature][Webhooks] Calculate Incident Age for Incidents send via Webhooks

### ISSUE THREAD

**Issue by Audefleda** [apache/devlake#8058]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a Dora Metrics user, I would like to have the Incident Age calculated for incidents, that are send via the Webhooks interface.

### Description

Currently it seems, that the incident age is not calculated for Incidents provided via webhooks. At least the "lead_time_minutes" field remains 0, although created_date and resolution_date are properly filled. The documentation, at least indicates, that this is only calculated for Jira and Github issues.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by Startrekzky** [comment]
Hi @Audefleda , we've considered this before, but we're not sure if anyone needs this. We can add this logic for sure.

**Comment by Audefleda** [comment]
Hi @Startrekzky ,
that sounds cool!

**Comment by Audefleda** [comment]
Hi @Startrekzky,
are you still planning to fix this issue?

**Comment by Startrekzky** [comment]
Hi @Audefleda , we are not going to do do this in the short term since it's not on our critical path. Sorry about that.

As a workaround, you could do:
- Fix the existing webhook data: Update the `issue_lead_time` data in your DevLake database directly.
- Adjust your webhook's payload to post the measured `issue_lead_time` to DevLake.

Feel free to reopen the issue if you still have questions.
