### ISSUE TITLE
[Question][Grafana] How to explore DevLake data and build dashboard in non-default organization of Grafana

### ISSUE THREAD

**Issue by DevOpsAutomationCloud** [apache/devlake#8160]
## Question
When create a new organization in Grafana, no data or dashboards are available in new organization.
I export dashboard from default organization and import into the new organization, but then I found no data available.
Config the mysql data source in new organization, connection is good but still no data show up in dashboard.
What else need to be done in order to have build-in dashboard available in new organization? 

## Screenshots
If applicable, add screenshots to help explain.

## Additional context
Add any other context here.

**Comment by diwangcanada** [comment]
ok, I found out the root cause, when copy dashboard into new organization, it copied the old data source id used by default organization.
In new organization, the data source id is different even through you make the name same.
So replace all old data source id with the new data source id, then it works now.
I think DevLake really need to document this to help people to use Grafana.
